---
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db:5432
      - ADMINER_DEFAULT_USERNAME=postgres
      - ADMINER_DEFAULT_PASSWORD=postgres    